title: Electronics Reference
author: ElectronicsReference
email: contact@electronicsreference.com
description: > # this means to ignore newlines until "baseurl:"
  This site will function as a code and project data repository for the main page at http://electronicsreference.com
 

# social links
github_username:  ElectronicsReference # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima

